function login

global usrname;
global usrpswd;
global adrs;
global state;
global cftp;
hLogin = figure('Units','Pixels',...
                'Position', [500 200 400 300],...
                'MenuBar','none',...
                'ToolBar','none',...
                'CloseRequestFcn',@closereq,...
                'Resize', 'off',...
                'Name', 'Chat Login');
            
%%INITALIZES THE UICONTROL FOR THIS GUI
loginP = uipanel(hLogin,'Units','normalized','Position',[.02 .02 .96 .96]);

%Pushbuttons first
loginPB = uicontrol('Style','pushbutton',...
                'FontSize',12,...
                'String','Login',...
                'Units','normalized',...  
                'Callback',@loginPB_CallBack,...
                'Position',[.03 .05 .3 .1]);
quitPB = uicontrol('Style','pushbutton',...
                'FontSize',12,...
                'String','Quit',...
                'Units','normalized',...
                'Callback',@quitPB_callback,...
                'Position',[.67 .05 .3 .1]);
helpPB = uicontrol('Style','pushbutton',...
                'FontSize',12,...
                'String','Help',...
                'Units','normalized',...
                'Callback',@helpPB_callback,...
                'Position',[.35 .05 .3 .1]);
            
%next is static text           
titleST = uicontrol(loginP,'Style','text',...
                'FontSize',14,...
                'FontWeight', 'Bold',...
                'String','LOGIN INFORMATION',...
                'Units','normalized',...
                'Position',[.15 .85 .7 .1]);
serverST = uicontrol(loginP,'Style','text',...
                'FontSize',12,...
                'String','Server:',...
                'HorizontalAlignment', 'right',...
                'Units','normalized',...
                'Position',[.09 .65 .3 .1]);
usernameST = uicontrol(loginP,'Style','text',...
                'FontSize',12,...
                'String','Username:',...
                'HorizontalAlignment', 'right',...
                'Units','normalized',...
                'Position',[.09 .45 .3 .1]);
passST = uicontrol(loginP,'Style','text',...
                'FontSize',12,...
                'String','Password:',...
                'HorizontalAlignment', 'right',...
                'Units','normalized',...
                'Position',[.09 .25 .3 .1]);
            
%last is textboxes           
serverTB = uicontrol(loginP,'Style','edit',...
                'String','192.168.1.6',...
                'Units','normalized',...
                'tag', 'serverTB',...
                'Position',[.4 .65 .5 .1]);
usernameTB = uicontrol(loginP,'Style','edit',...
                'String','',...
                'Units','normalized',...
                'tag', 'usernameTB',...
                'Position',[.4 .45 .5 .1]);
passTB = uicontrol(loginP,'Style','edit',...
                'String','',...
                'Units','normalized',...
                'tag', 'passTB',...
                'KeyPressfcn',{@KeyPress_Function,hLogin},...
                'Userdata','',...
                'Position',[.4 .25 .5 .1]);
%% END INSTANTIATION
uiwait(hLogin);
    %help butotn callback, it displays the information to help the user
    %login to the server
    function helpPB_callback(src, event)
        msgbox({'Welcome to Group 3''s encrypted chat help box.' ' ' 'To login:'...
                'First, enter the IP address of the FTP server.' 'If you don''t know it, use ipconfig on the server to find out.'...
                'Next, enter a valid user name for that FTP server.' 'Last, enter the password for that user.'...
                ' ' 'If you are having trouble logging in, check that the server is running and that you are correctly typing in your credentials'}, 'Help');
    end
%login button, it takes the information stored in the figure and attempts
%to log into the FTP server. If it can't log on or times out, it will throw
%and error message box
function loginPB_CallBack(src, event)
    fig = ancestor(src, 'figure');
    haddres = findobj( 'tag', 'serverTB');
    hname = findobj('tag', 'usernameTB');
    hpass = findobj('tag', 'passTB');
    adrs = get(haddres, 'String');
    usrname = get(hname, 'String');
    usrpswd = get(hpass, 'Userdata');

    
    try
        cftp = ftp(adrs, usrname,usrpswd);%log on to ftp server
        state = 2; %%goes to state 2 aka select chat
        uiresume(fig);%resume the state machine
        closereq(src);%try to close the gui
    catch ME
        msgbox({'Unable to connect to FTP server.' 'Please check the server address, username, and password.' }, 'Connection Error','error');
        disp(ME);
    end
    
end
%quit button tries to close the program by going to state 5, aka close
%state
function quitPB_callback (src, event)
    closereq;
end

%close request function, if the src was included then there is a next state
%other than closing the application
function closereq(hObject, eventdata, handles)
    if nargin == 1
        %%don't change the next state
    else
        state = 5; %%goes to state 5 aka close
    end
    delete(gcf);%deletes the GUI
end

function KeyPress_Function(h,eventdata,fig)
% Function to replace all characters in the password edit box with
% asterisks
password = get(h,'Userdata');
key = get(fig,'currentkey');

switch key
    case 'backspace'
        password = password(1:end-1); % Delete the last character in the password
    case 'return'  % This cannot be done through callback without making tab to the same thing
        loginPB_CallBack(h, eventdata)
        return;
    otherwise
        password = [password get(fig,'currentcharacter')]; % Add the typed character to the password
end

SizePass = size(password); % Find the number of asterisks
if SizePass(2) > 0
    asterisk(1,1:SizePass(2)) = '*'; % Create a string of asterisks the same size as the password
    set(h,'String',asterisk) % Set the text in the password edit box to the asterisk string
else
    set(h,'String','')
end

set(h,'Userdata',password) % Store the password in its current state
end
end
